# Задание
Имеются данные adult.csv (см. в материалах к занятию).
Целевой переменной является уровень дохода income (крайний правый столбец).
Описание признаков можно найти по ссылке www.cs.toronto.edu...etail.html
Вам необходимо построить модели логистической регрессии и SVM, которые предсказывает уровень дохода человека.
Вывести качество полученных моделей на тестовой выборке, используя функцию score у модели.
Готовый ноутбук выложить на гитхаб и прислать ссылку.

<h2>Логистическая регрессия</h2>

In [ ]:
import numpy as np
import pandas as pd # Для работы с данными
import scipy.stats # При работе со статистикой
import matplotlib.pyplot as plt  # Библиотека для визуализации результатов 

In [101]:
# Download the data 
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',header=None) # датасет - https://www.kaggle.com/rio2016/olympic-games

#data = pd.read_csv('https://raw.githubusercontent.com/a-milenkin/datasets_for_t-tests/main/athletes.csv') # датасет - https://www.kaggle.com/rio2016/olympic-games
data.head(20)

0                  1       2              3   4                       5   \
0   39          State-gov   77516      Bachelors  13           Never-married   
1   50   Self-emp-not-inc   83311      Bachelors  13      Married-civ-spouse   
2   38            Private  215646        HS-grad   9                Divorced   
3   53            Private  234721           11th   7      Married-civ-spouse   
4   28            Private  338409      Bachelors  13      Married-civ-spouse   
5   37            Private  284582        Masters  14      Married-civ-spouse   
6   49            Private  160187            9th   5   Married-spouse-absent   
7   52   Self-emp-not-inc  209642        HS-grad   9      Married-civ-spouse   
8   31            Private   45781        Masters  14           Never-married   
9   42            Private  159449      Bachelors  13      Married-civ-spouse   
10  37            Private  280464   Some-college  10      Married-civ-spouse   
11  30          State-gov  141297      Bachelors  13      Married-civ-spouse   
12  23            Private  122272      Bachelors  13           Never-married   
13  32            Private  205019     Assoc-acdm  12           Never-married   
14  40            Private  121772      Assoc-voc  11      Married-civ-spouse   
15  34            Private  245487        7th-8th   4      Married-civ-spouse   
16  25   Self-emp-not-inc  176756        HS-grad   9           Never-married   
17  32            Private  186824        HS-grad   9           Never-married   
18  38            Private   28887           11th   7      Married-civ-spouse   
19  43   Self-emp-not-inc  292175        Masters  14                Divorced   

                    6               7                    8        9      10  \
0         Adm-clerical   Not-in-family                White     Male   2174   
1      Exec-managerial         Husband                White     Male      0   
2    Handlers-cleaners   Not-in-family                White     Male      0   
3    Handlers-cleaners         Husband                Black     Male      0   
4       Prof-specialty            Wife                Black   Female      0   
5      Exec-managerial            Wife                White   Female      0   
6        Other-service   Not-in-family                Black   Female      0   
7      Exec-managerial         Husband                White     Male      0   
8       Prof-specialty   Not-in-family                White   Female  14084   
9      Exec-managerial         Husband                White     Male   5178   
10     Exec-managerial         Husband                Black     Male      0   
11      Prof-specialty         Husband   Asian-Pac-Islander     Male      0   
12        Adm-clerical       Own-child                White   Female      0   
13               Sales   Not-in-family                Black     Male      0   
14        Craft-repair         Husband   Asian-Pac-Islander     Male      0   
15    Transport-moving         Husband   Amer-Indian-Eskimo     Male      0   
16     Farming-fishing       Own-child                White     Male      0   
17   Machine-op-inspct       Unmarried                White     Male      0   
18               Sales         Husband                White     Male      0   
19     Exec-managerial       Unmarried                White   Female      0   

    11  12              13      14  
0    0  40   United-States   <=50K  
1    0  13   United-States   <=50K  
2    0  40   United-States   <=50K  
3    0  40   United-States   <=50K  
4    0  40            Cuba   <=50K  
5    0  40   United-States   <=50K  
6    0  16         Jamaica   <=50K  
7    0  45   United-States    >50K  
8    0  50   United-States    >50K  
9    0  40   United-States    >50K  
10   0  80   United-States    >50K  
11   0  40           India    >50K  
12   0  30   United-States   <=50K  
13   0  50   United-States   <=50K  
14   0  40               ?    >50K  
15   0  45          Mexico   <=50K  
16   0  35   United-States   <=50K

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       32561 non-null  int64 
 1   1       32561 non-null  object
 2   2       32561 non-null  int64 
 3   3       32561 non-null  object
 4   4       32561 non-null  int64 
 5   5       32561 non-null  object
 6   6       32561 non-null  object
 7   7       32561 non-null  object
 8   8       32561 non-null  object
 9   9       32561 non-null  object
 10  10      32561 non-null  int64 
 11  11      32561 non-null  int64 
 12  12      32561 non-null  int64 
 13  13      32561 non-null  object
 14  14      32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [103]:
from sklearn.linear_model import LogisticRegression

In [104]:
# попробуем выбрать какие-нибудь признаки, для начала
selectedColumns = data[[1, 3, 6, 13, 14]]

In [105]:
X = pd.get_dummies (selectedColumns, columns = [1, 3, 6, 13])

In [106]:
del X[14]
X.head()

1_ ?  1_ Federal-gov  1_ Local-gov  1_ Never-worked  1_ Private  \
0     0               0             0                0           0   
1     0               0             0                0           0   
2     0               0             0                0           1   
3     0               0             0                0           1   
4     0               0             0                0           1   

   1_ Self-emp-inc  1_ Self-emp-not-inc  1_ State-gov  1_ Without-pay  \
0                0                    0             1               0   
1                0                    1             0               0   
2                0                    0             0               0   
3                0                    0             0               0   
4                0                    0             0               0   

   3_ 10th  ...  13_ Portugal  13_ Puerto-Rico  13_ Scotland  13_ South  \
0        0  ...             0                0             0          0   
1        0  ...             0                0             0          0   
2        0  ...             0                0             0          0   
3        0  ...             0                0             0          0   
4        0  ...             0                0             0          0   

   13_ Taiwan  13_ Thailand  13_ Trinadad&Tobago  13_ United-States  \
0           0             0                    0                  1   
1           0             0                    0                  1   
2           0             0                    0                  1   
3           0             0                    0                  1   
4           0             0                    0                  0   

   13_ Vietnam  13_ Yugoslavia  
0            0               0  
1            0               0  
2            0               0  
3            0               0  
4            0               0  

[5 rows x 82 columns]

In [107]:
# целевая переменная (столбец sex) снова является категориальной 
# переведем значения столбца в числа, оставив один столбец

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [108]:
le.fit( data[14])

LabelEncoder()

In [109]:
print(le.classes_)
print(le.transform(le.classes_)) # пример расшифровки
le.transform(le.classes_)

[' <=50K' ' >50K']
[0 1]


array([0, 1])

In [110]:
le.transform(le.classes_) # пример расшифровки

array([0, 1])

In [111]:
# записываем в таргетную переменную y преобразованный столбец sex

y = pd.Series (data = le.transform(data[14]))
y.head()

0    0
1    0
2    0
3    0
4    0
dtype: int32

In [167]:
from sklearn.pipeline import make_pipeline # используем пайплайны для удобства
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 

model = make_pipeline(StandardScaler(), LogisticRegression(solver='lbfgs',max_iter=10000))

In [168]:
model = LogisticRegression()

**<p>**Шаг 2 Текст, выделенный полужирным шрифтом. Обучение. Поделим данные на обучающую выборку и тестовую. Указываем в test_size долю датасета, которая пойдет на тестовую выбору</p**>**

In [169]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [170]:
y_train.head()

19749    0
1216     1
27962    0
23077    0
10180    0
dtype: int32

In [171]:
X_train.head()

1_ ?  1_ Federal-gov  1_ Local-gov  1_ Never-worked  1_ Private  \
19749     0               0             0                0           0   
1216      0               0             0                0           0   
27962     0               0             0                0           0   
23077     0               0             1                0           0   
10180     0               0             0                0           1   

       1_ Self-emp-inc  1_ Self-emp-not-inc  1_ State-gov  1_ Without-pay  \
19749                0                    1             0               0   
1216                 0                    1             0               0   
27962                0                    0             1               0   
23077                0                    0             0               0   
10180                0                    0             0               0   

       3_ 10th  ...  13_ Portugal  13_ Puerto-Rico  13_ Scotland  13_ South  \
19749        0  ...             0                0             0          0   
1216         0  ...             0                0             0          0   
27962        0  ...             0                0             0          0   
23077        0  ...             0                0             0          0   
10180        0  ...             0                0             0          0   

       13_ Taiwan  13_ Thailand  13_ Trinadad&Tobago  13_ United-States  \
19749           0             0                    0                  1   
1216            0             0                    0                  1   
27962           0             0                    0                  1   
23077           0             0                    0                  1   
10180           0             0                    0                  1   

       13_ Vietnam  13_ Yugoslavia  
19749            0               0  
1216             0               0  
27962            0               0  
23077            0               0  
10180            0               0  

[5 rows x 82 columns]

In [172]:
# обучаем на части датасета (train)

model.fit(X_train, y_train)
predictions = model.predict(X_test)

C:\users\emaxkra\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [173]:
predictions[1000:1100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [174]:
model.predict(X_test)

array([0, 0, 1, ..., 0, 0, 0])

In [175]:
model.predict_proba(X_test)

array([[0.88327042, 0.11672958],
       [0.75407839, 0.24592161],
       [0.44545711, 0.55454289],
       ...,
       [0.69135673, 0.30864327],
       [0.77775646, 0.22224354],
       [0.60015298, 0.39984702]])

In [176]:
model.score(X_train, y_train) 

0.7894875394875395

In [164]:
model.score(X_test,y_test)

0.7892312416828744

# Метод опорных векторов. SVM

In [177]:
from sklearn.svm import SVC
# используем пайплайны
clf = make_pipeline(StandardScaler(), SVC(gamma='auto')) 
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [178]:
clf.score(X_train, y_train) 

0.7944892944892945

In [179]:
clf.score(X_test,y_test)

0.7917903572525335

In [180]:
clf = make_pipeline(SVC(gamma='auto')) 

In [181]:
clf.fit(X_train, y_train)

Pipeline(steps=[('svc', SVC(gamma='auto'))])

In [182]:
clf.score(X_train, y_train) 

0.7784310284310284

In [183]:
clf.score(X_test,y_test)

0.7822704473334016